network:
 version: 2
 renderer: networkd
 ethernets:
    enp0s3:
       dhcp4: no
       dhcp6: no
       addresses: [192.168.1.16/24]
       gateway4: 192.168.1.1
       nameservers:
          addresses: [192.168.1.1,8.8.8.8]
